# Generated by Django 5.1.1 on 2024-09-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pitanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('car_brand', models.CharField(choices=[], max_length=30)),
                ('car_model', models.CharField(choices=[], max_length=30)),
                ('body_type', models.CharField(choices=[], max_length=30)),
                ('question', models.TextField(max_length=2500)),
            ],
        ),
    ]
